name: CODE-BROWSER

on:
  workflow_dispatch:

jobs:
  ubuntu-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 345

    steps:
      - name: Update system
        run: |
          sudo apt update -y
          

      - name: Install desktop (XFCE) + VNC
        run: |
          sudo apt install -y \
            curl wget unzip \
            net-tools

      - name: Start virtual display
        run: |
          export DISPLAY=:0
          ls

      - name: Start XFCE desktop
        run: |
          export DISPLAY=:0
          ls


      - name: Start VNC server
        run: |
          export DISPLAY=:0
          ls


      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscaled &
          sleep 5
          # 1. Your Base64 encoded key
          base64Key="dHNrZXktYXV0aC1rR2pmdFZ2dWVFMTFDTlRSTC1oUWpaSzJxZHBMaE56dEdLYlVXeUxoVFltSDc1eTJLTA=="
          # 2. Decode the key 
          # NOTICE: Linux uses lowercase '-d' for decoding
          authKey=$(echo -n "$base64Key" | base64 -d)
          echo "Auth key successfully decoded on Linux."
          # 3. Run Tailscale Up
          # Using sudo is standard for Linux network changes
          sudo tailscale up --authkey="$authKey" --hostname=linux-host
          tailscale ip -4

      - name: Install sshx
        run: |
          curl -sSf https://sshx.io/get | sh
          echo "=== SSHX URL BELOW ==="
          sshx 2>&1 &

      - name: Download Sunshine
        run: |
          ls
          # wget https://github.com/LizardByte/Sunshine/releases/download/v2025.924.154138/sunshine-ubuntu-24.04-amd64.deb -O sunshine.deb

      - name: Install Sunshine
        run: |
          # sudo apt install -y ./sunshine.deb || true

      - name: Run Sunshine
        run: |
          # sunshine &
          sleep 5
          # ps aux | grep sunshine || true
          curl -fsSL https://code-server.dev/install.sh | sh
          
          code-server \
            --install-extension davidanson.vscode-markdownlint \
            --install-extension donjayamanne.githistory \
            --install-extension moonshot-ai.kimi-code \
            --install-extension eamodio.gitlens 
          

      - name: Keep alive (5h 45m)
        run: |
          echo "Keeping runner alive..."
          tailscale ip
          cat ~/.config/code-server/*
          code-server --bind-addr 0.0.0.0:8080 &
          
          echo "End time: $(date -d '+5 hours 45 minutes')"

          for i in $(seq 1 345); do
            echo "Minute $i / 345 — $(date)"
            sleep 60
          done
